# Generated by Django 5.2 on 2025-04-23 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('inn', models.BigIntegerField(unique=True, verbose_name='ИНН')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('achievements', models.TextField(verbose_name='Достижения')),
                ('rank', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Место в рейтинге')),
                ('bonus_points', models.IntegerField(default=0, verbose_name='Бонусные баллы')),
            ],
            options={
                'verbose_name': 'Волонтёр',
                'verbose_name_plural': 'Волонтёры',
                'ordering': ['rank'],
            },
        ),
    ]
