"""
<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
Django settings for volunteer_platform project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
========
Django settings for volpol project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

>>>>>>>> origin/volpol:volpol/volpol/settings.py
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j8%^3+wzcch+#n1wanya!f)#h#!yj()zrt)(%w^-tz@d*mb@hh'
========
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n$tu%3d$f*vml9(l!i&d-s9p%j+r#=nq@*yfzl)ft_g@74*8jg'
>>>>>>>> origin/volpol:volpol/volpol/settings.py

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
========
    'volpol',
>>>>>>>> origin/volpol:volpol/volpol/settings.py
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
    'volunteers',
    'crispy_forms',
    'crispy_bootstrap5',
]
AUTH_USER_MODEL = 'volunteers.User'  # Кастомная модель пользователя

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
CRISPY_TEMPLATE_PACK = 'bootstrap5'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'login_redirect'  # Используем новую систему перенаправления
========
]

>>>>>>>> origin/volpol:volpol/volpol/settings.py
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
ROOT_URLCONF = 'volunteer_platform.urls'
========
ROOT_URLCONF = 'volpol.urls'
>>>>>>>> origin/volpol:volpol/volpol/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
========
        'DIRS': [],
>>>>>>>> origin/volpol:volpol/volpol/settings.py
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
WSGI_APPLICATION = 'volunteer_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
========
WSGI_APPLICATION = 'volpol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
>>>>>>>> origin/volpol:volpol/volpol/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
========
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
>>>>>>>> origin/volpol:volpol/volpol/settings.py

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
# https://docs.djangoproject.com/en/5.2/topics/i18n/
========
# https://docs.djangoproject.com/en/5.1/topics/i18n/
>>>>>>>> origin/volpol:volpol/volpol/settings.py

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
# https://docs.djangoproject.com/en/5.2/howto/static-files/
========
# https://docs.djangoproject.com/en/5.1/howto/static-files/
>>>>>>>> origin/volpol:volpol/volpol/settings.py

STATIC_URL = 'static/'

# Default primary key field type
<<<<<<<< HEAD:volpol/volunteer_platform/settings.py
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
========
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
>>>>>>>> origin/volpol:volpol/volpol/settings.py

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
